[[Nettle]]
arch = "i686"
git-tree-sha1 = "8084212b22f57b35665fc611d716156b813cade8"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "79742aa84b4a7c67095c4229cfdae5087fd75fce707f585b3c28b9d23ddacd8d"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.4.1+1/Nettle.v3.4.1.i686-linux-musl.tar.gz"
[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "46ab23c0158a4d79efe15d04763a7d4b2e6aabd5"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "b28d3cf46262cdffbd6ef36037070c0e17a50b488c2b75229940b1ef512e1330"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.4.1+1/Nettle.v3.4.1.aarch64-linux-musl.tar.gz"
[[Nettle]]
arch = "i686"
git-tree-sha1 = "a6e95463c996dc2655a2f11cc1a302c5040cfee8"
os = "windows"

    [[Nettle.download]]
    sha256 = "00adba7a15c1e5a8c69148c55cc8b14e6efa8be061ce0807da502b89fbc1a95c"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.4.1+1/Nettle.v3.4.1.i686-w64-mingw32.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "0b09396f456c54d28b994dbadb0c1113c93be7af"
os = "windows"

    [[Nettle.download]]
    sha256 = "0925e03556604b59dc1fba59a44393f8fe661bfd14270c248ec9bdd85e04942a"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.4.1+1/Nettle.v3.4.1.x86_64-w64-mingw32.tar.gz"
[[Nettle]]
arch = "armv7l"
git-tree-sha1 = "5514ea8c5e03e583ae5a36e89da5893a34cad999"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "3568636d7bb3e6199f4fcd4b769bd13b17c473f8f0ac2fb690005fa1a973ac41"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.4.1+1/Nettle.v3.4.1.armv7l-linux-gnueabihf.tar.gz"
[[Nettle]]
arch = "armv7l"
git-tree-sha1 = "1467c2c7476a5f55c067fb78002cd706cb2cdcc8"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "08b8b346f8ce9cf4bcfdaf726bdae08aac31f92228dd762747b62dfeb87cedfb"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.4.1+1/Nettle.v3.4.1.armv7l-linux-musleabihf.tar.gz"
[[Nettle]]
arch = "i686"
git-tree-sha1 = "dda39ca33fb1d960510fb3adb203a3d5b28d0b2c"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "b6b328702ce0c799d492100a97b90f245ed77cc55ed4bdd00977827f55124dee"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.4.1+1/Nettle.v3.4.1.i686-linux-gnu.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "bb1fd699e08d76f0492c3b6c3f6fa79dd10924be"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "f75fcd52467209a427bb2341ff7424f40d039a836c3deebdc0a95a13b7c16bc7"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.4.1+1/Nettle.v3.4.1.x86_64-linux-gnu.tar.gz"
[[Nettle]]
arch = "powerpc64le"
git-tree-sha1 = "cd618f1d6e84e245a6a4d4f0143b57eb0fed9258"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "a932e3d78d6f0d9a146a654414bbcc287d2bc1669fb8c667028fdde87e2d6ade"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.4.1+1/Nettle.v3.4.1.powerpc64le-linux-gnu.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "fbbdb2a59dcdda220a99c3a6abd74286251a4e7b"
os = "macos"

    [[Nettle.download]]
    sha256 = "049cfd0e04d0bfc6786189068cfa9bc4dcfbacc897c9268c049cdd44376810e7"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.4.1+1/Nettle.v3.4.1.x86_64-apple-darwin14.tar.gz"
[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "8f2e682c78a10e92a26e9e82a8e5fc151e701401"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "595fb3a3c42bd97774a95e37ae9160fc6964ad0508f45425d01a0344819ae736"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.4.1+1/Nettle.v3.4.1.aarch64-linux-gnu.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "b29539fc05d52f56ab6817787e2bbd2718e76b3b"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "7be8760c34633121cfcbe691adc9bfe54be4527b6b59ebd4536fcf1407d5b032"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.4.1+1/Nettle.v3.4.1.x86_64-linux-musl.tar.gz"
