[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "ffe020d9d683de3dbfd472b7b60dcd2a3a869c38"
os = "macos"

    [[Nettle.download]]
    sha256 = "b3127645bd4e43b042fce075b152caaf9c389fe04d5948084ff9c01e8dd8e077"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+1/Nettle.v3.10.0.aarch64-apple-darwin.tar.gz"
[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "235f24b35893044ee8858d90d87ae45c5102ac1d"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "13766ef52892f24c7c9fc3f02302657c7622d0382546abc65df092d2f586b4b9"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+1/Nettle.v3.10.0.aarch64-linux-gnu.tar.gz"
[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "cb2e3401fd8b3b46b93a4d376a9728ab03f51707"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "63a9a8dfb085a88457afe8bf9513a9c10a081bf59c4466e787d2665995885fa6"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+1/Nettle.v3.10.0.aarch64-linux-musl.tar.gz"
[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "395e18b5685a610a4832cebf287f06b47fa2f6ec"
os = "freebsd"

    [[Nettle.download]]
    sha256 = "c61cea9d739136c81da34933b49d40c4fc63a201f6a9c8bf1a2ff2b387599459"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+1/Nettle.v3.10.0.aarch64-unknown-freebsd.tar.gz"
[[Nettle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "895eccea26f023b1ea43e72a3f885685eb107676"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "3e4c9053249fa5d6ed6d2c981b215c19db9cfaebfb4b26f485f4f9839600d15d"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+1/Nettle.v3.10.0.armv6l-linux-gnueabihf.tar.gz"
[[Nettle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cbae5dbb67a8a1ee9eb943f3ec6399ef2ba56e13"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "f340f8cf6b64581a5459f1cecd13a6052d3a51c6a573f3ce6ea627ab75cf1649"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+1/Nettle.v3.10.0.armv6l-linux-musleabihf.tar.gz"
[[Nettle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "63d6243261e056d4fd00cfa4fb7609ffea5164fb"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "ec3f9d2ca04c0f72d23c9e460b0fe95e32856aa24fe35f8001ba8ea8cad3fd49"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+1/Nettle.v3.10.0.armv7l-linux-gnueabihf.tar.gz"
[[Nettle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "53f1c9ea91582925fcc4ccdab5fb8b3f5094f5dd"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "dcf2684df83eb35af92da4296ac7356817f4d2c70d7d787f4005f851eaff1b48"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+1/Nettle.v3.10.0.armv7l-linux-musleabihf.tar.gz"
[[Nettle]]
arch = "i686"
git-tree-sha1 = "9619758f42433c6ff937f3f4ee921b3146776cd4"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "0e401e01e5f7c2f93132a8ec61698f167c67d3e3d0d943069fa09b4265fe4638"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+1/Nettle.v3.10.0.i686-linux-gnu.tar.gz"
[[Nettle]]
arch = "i686"
git-tree-sha1 = "43f15123079ef8fb7fe5d9b3e6bba7b83846e976"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "adf35653021121d7c82d886cae74feda358792ee00bcd5aa999e7aee57d60e38"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+1/Nettle.v3.10.0.i686-linux-musl.tar.gz"
[[Nettle]]
arch = "i686"
git-tree-sha1 = "7088a4bd75323db2b66bf56b9a63c6173c5c68c7"
os = "windows"

    [[Nettle.download]]
    sha256 = "25716b9b86f1714dd7ae80fe36974f57b552ae40d50f68a2d796c34da14877e1"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+1/Nettle.v3.10.0.i686-w64-mingw32.tar.gz"
[[Nettle]]
arch = "powerpc64le"
git-tree-sha1 = "08c1972a3432928bd8c18375e68600b1bdd545a5"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "592a6a8d73086578feed01744b3d89bfcc9720937ec42701206179161274ff2b"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+1/Nettle.v3.10.0.powerpc64le-linux-gnu.tar.gz"
[[Nettle]]
arch = "riscv64"
git-tree-sha1 = "2b3eb73b29d1d91f8d311620b086d0f0b30a9f1f"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "93836200f986dfb02fa072a17a6c5700d7f8aa33b8b93c77b3eb6afcecaa8045"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+1/Nettle.v3.10.0.riscv64-linux-gnu.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "7c00861b49e54cd43b81b3a6cf62a8e6dac9ad77"
os = "macos"

    [[Nettle.download]]
    sha256 = "fa0ba335914ba69dbaf88ad093fa4cbcab87efbb73984d72ad932a173046f092"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+1/Nettle.v3.10.0.x86_64-apple-darwin.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "810641579cf275577bd2f1e93ce2766793f63c20"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "c70c4bd585b18fbb4a6899cd2ab295226620b09f7d93908a10786d0d71d2928c"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+1/Nettle.v3.10.0.x86_64-linux-gnu.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "7e752fa38231298df2472a1af263750f7fe780fb"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "1ffba18970f4b8146a7d359ff1f26277107d29b26abe494f614ec69ec4744803"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+1/Nettle.v3.10.0.x86_64-linux-musl.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "624229f6650c8593cdcf920e770373571f3f243e"
os = "freebsd"

    [[Nettle.download]]
    sha256 = "3baa59330f5bb450831dff1b954f96e74e388fb43cb3a323bc7eecd09927dad1"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+1/Nettle.v3.10.0.x86_64-unknown-freebsd.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "78ae1fcdda5743ffd5ff56c5a8afee023e222810"
os = "windows"

    [[Nettle.download]]
    sha256 = "e73117cdabd59437ce39d7bd0f79197568a0bee9656c8e165b7289b165ee2788"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+1/Nettle.v3.10.0.x86_64-w64-mingw32.tar.gz"
