[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "549e8e5271750c14d78c5f1a9eddddea3ce62b8a"
os = "macos"

    [[Nettle.download]]
    sha256 = "b2a2a66dab3f4765b63f6dfcca084b8a6bed281d61e6520188c6243a3a12ca21"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.9.1+0/Nettle.v3.9.1.aarch64-apple-darwin.tar.gz"
[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "d42f0a9d8d21e29adf09678b82df67691d7a0c26"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "27aded51edb0209018a1af6af897ae1d7ae10652979ca94e11022169897fe88f"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.9.1+0/Nettle.v3.9.1.aarch64-linux-gnu.tar.gz"
[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "28a531ea7fc213292fcb118c454139999aa3266c"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "e5645ad89dd07d221a4a7b073ae8e6469932101253b5f8ff195ff28cec72f6ef"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.9.1+0/Nettle.v3.9.1.aarch64-linux-musl.tar.gz"
[[Nettle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cd0d3c2a00c4f0b54951334c8558d1fd5b4330e4"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "15ed094fd8356e39b2a2c18042212d6dadf44657c105857ec819cd66db724c39"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.9.1+0/Nettle.v3.9.1.armv6l-linux-gnueabihf.tar.gz"
[[Nettle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "702913d353639ebbb2ce0d319e82680400da619a"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "c179a1d398e41f3391a9bd154826dd1ef5dd43629656d3c51652f8c0537cd058"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.9.1+0/Nettle.v3.9.1.armv6l-linux-musleabihf.tar.gz"
[[Nettle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3cd2945b4ae0b8329fc8a17523bd5da536d52f79"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "eef2de8a790550b690a25403fe99a9c7ada6b1215c044349346dba55b005816a"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.9.1+0/Nettle.v3.9.1.armv7l-linux-gnueabihf.tar.gz"
[[Nettle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6a7bde1a38c07f95fe70983596a84d41ed4e6c7e"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "0c0337cce76100b5fb483ae812e2ea82a69cf5600061a58f79378fed138e22f0"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.9.1+0/Nettle.v3.9.1.armv7l-linux-musleabihf.tar.gz"
[[Nettle]]
arch = "i686"
git-tree-sha1 = "4d0f6de5794901175953f8b946b176975f4f5bff"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "0a6ea399361768d50d40d720043af5f3d62cf4f489eb7d505538976d4f54a650"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.9.1+0/Nettle.v3.9.1.i686-linux-gnu.tar.gz"
[[Nettle]]
arch = "i686"
git-tree-sha1 = "ca82b9ed24c6fa590dd0137ae8f6f132aacaddac"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "99df20b26c9f098146efb77a6459f8c3ead634e29f6144f293dd69dea9eba0aa"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.9.1+0/Nettle.v3.9.1.i686-linux-musl.tar.gz"
[[Nettle]]
arch = "i686"
git-tree-sha1 = "80430621dca55358d8d6ebe163f3e337226f000b"
os = "windows"

    [[Nettle.download]]
    sha256 = "26906f9205ab22fbca4ac1f449ab3534c47eadd2b9e9f48fd80c3410981cd665"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.9.1+0/Nettle.v3.9.1.i686-w64-mingw32.tar.gz"
[[Nettle]]
arch = "powerpc64le"
git-tree-sha1 = "a196499969f42b0de2d77c916eeb900293d5814b"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "37fd69a13c8663f7e008eb10a1529c12457ead91a7480ecacf49c5f2779c980f"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.9.1+0/Nettle.v3.9.1.powerpc64le-linux-gnu.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "60c1c17e259b4a9d24f40e8324d4a6f7be8063f1"
os = "macos"

    [[Nettle.download]]
    sha256 = "69a60137c7a203834095708ebf534e1a5f64ba2a70b48600b59d65aff673e6b7"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.9.1+0/Nettle.v3.9.1.x86_64-apple-darwin.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "07c1e30f677d4c4dafdb1cf609d2f2ce077e3043"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "3a1a23fec116e14e4464debf7e8bdcd50a8d631cb7faf17f853fd57d1438afd1"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.9.1+0/Nettle.v3.9.1.x86_64-linux-gnu.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "33a7ef5deb962e40c925940e6341882e65db25cc"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "7e9bca3714ad3d75e646cf70e570e85d29bff3bae9ee4565c6c219d82859c7a3"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.9.1+0/Nettle.v3.9.1.x86_64-linux-musl.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "d3764cfcf36feb35624f2267c835dcf9c1e6b91c"
os = "freebsd"

    [[Nettle.download]]
    sha256 = "8e20cfdf13e31e1abc994d4bdb0579c12cc748ab7c71b8ed821f7b4fd4ea5705"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.9.1+0/Nettle.v3.9.1.x86_64-unknown-freebsd.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "b073024d4c034c715cb7d04639b65a20038a6997"
os = "windows"

    [[Nettle.download]]
    sha256 = "071a6e2a25949a910a54a1b6106019850926b88f807445166ec4916c5970cf26"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.9.1+0/Nettle.v3.9.1.x86_64-w64-mingw32.tar.gz"
