[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "308ed67699815832aca4a1b842d253c04ad47e43"
os = "macos"

    [[Nettle.download]]
    sha256 = "fc480ff1bb1cb77a16cd28be74c42cbb6842bd54e9fd38af8b84e44cf0a3a8a8"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.1+0/Nettle.v3.10.1.aarch64-apple-darwin.tar.gz"
[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "be881ddb3cde0e672fe6b2a66188ec668f742d83"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "627e81933f25d0d13e8f1449be8c0b5d62af4d79535678beeeead1f753ac197e"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.1+0/Nettle.v3.10.1.aarch64-linux-gnu.tar.gz"
[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "1c328d57a2dc03c8cd92938dcd435c35da3691bc"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "898dae85bd777d4a074a07001e0935b8a724c143ed13ba637b65edcaff2c817f"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.1+0/Nettle.v3.10.1.aarch64-linux-musl.tar.gz"
[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "64b8941ade6550ebb6bc7633f688cd08417e8664"
os = "freebsd"

    [[Nettle.download]]
    sha256 = "80a2600720f87ffd445cbf4852c9d73b893d88e886bc280077138fbf38e1fb55"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.1+0/Nettle.v3.10.1.aarch64-unknown-freebsd.tar.gz"
[[Nettle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3d3a573cc6eaaf8e7d9f56743a3056a2c2f29d81"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "6c556091cf8949c89051b04ceb39e2ad7865b252a808614cc037e8a415c4665c"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.1+0/Nettle.v3.10.1.armv6l-linux-gnueabihf.tar.gz"
[[Nettle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "253142b53f841c0ea725b0d6e4ee04594e6b97f0"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "b4dba78cc6996d12a00af6685a694dcb193d65cb14102f6ce49b91d527b54b92"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.1+0/Nettle.v3.10.1.armv6l-linux-musleabihf.tar.gz"
[[Nettle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5acca030ab1162503ee7699b61ca16761fb6b63b"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "7502dfd4a2cded0e56e7f1e8c1f35554062371024777d795a004ff72868ce312"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.1+0/Nettle.v3.10.1.armv7l-linux-gnueabihf.tar.gz"
[[Nettle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0b3b479a472b8448d7bf1a0440c8ed64898f02c4"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "12b90dbd2b4ef806d9f42c6d3b2827e1ef1aa669de6b6c890ab8c47571c8cc6d"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.1+0/Nettle.v3.10.1.armv7l-linux-musleabihf.tar.gz"
[[Nettle]]
arch = "i686"
git-tree-sha1 = "bc9df2ad8fdfc9c73e2be37efee77e3973db5102"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "7c573dfd7605afa07ee5d951dd6b35907794a3d778907a867daa2ad75ec0bd13"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.1+0/Nettle.v3.10.1.i686-linux-gnu.tar.gz"
[[Nettle]]
arch = "i686"
git-tree-sha1 = "268b6db71c10a0cfac32375ef41777978a43709d"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "b8f85a85795c54c7c4c764877c92f6aaad83bf04d8e6374f0d9afdba95d73bee"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.1+0/Nettle.v3.10.1.i686-linux-musl.tar.gz"
[[Nettle]]
arch = "i686"
git-tree-sha1 = "85b665a58371711ad694c589008add8d91641d4b"
os = "windows"

    [[Nettle.download]]
    sha256 = "1300b3697ea24c4457c59a73e5ab43e502c8a72f3a689a8f1db48983edd39c17"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.1+0/Nettle.v3.10.1.i686-w64-mingw32.tar.gz"
[[Nettle]]
arch = "powerpc64le"
git-tree-sha1 = "e7172318dd0fcb74382a53543d8c7c489c6c12d5"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "08b633345abaf158d007702a86ae4ed25d6c706f19919ece7307491164db9ba6"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.1+0/Nettle.v3.10.1.powerpc64le-linux-gnu.tar.gz"
[[Nettle]]
arch = "riscv64"
git-tree-sha1 = "7b904a4a5d076caaac000a02ffab54a7eeb1e827"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "17852201125fbd92b1b18e06b22c02a87b4cc54ac0bef84322e5c63afd35ac28"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.1+0/Nettle.v3.10.1.riscv64-linux-gnu.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "df8ce1c52e17f47a311bad1589cbc4f8bd2de115"
os = "macos"

    [[Nettle.download]]
    sha256 = "0751c8cdcc0aba86bc53df9f95d9e34b6cd17b008841210dd005a97dbf654dfe"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.1+0/Nettle.v3.10.1.x86_64-apple-darwin.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "29efbff8d30b4390c72b16b815a9fe6b878b2a1d"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "9ba76278b65d78e764e0baac35a832e83f2e08fac2cfa55f28481f5d8b9b7ab5"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.1+0/Nettle.v3.10.1.x86_64-linux-gnu.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "a65ffe2aa51a752e180d1bb5f5b08408da2a4e53"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "7ce84db5fc8d7461d2d68cdb61718459528b08222652b759450ce8713ca3c28d"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.1+0/Nettle.v3.10.1.x86_64-linux-musl.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "d25c46bfc899557c6ec9fe96876c2664d6a9d229"
os = "freebsd"

    [[Nettle.download]]
    sha256 = "6dff7b5640fd4863cf82473a000e01e8de4ecf6413c57a8e94ec370b5a97d5eb"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.1+0/Nettle.v3.10.1.x86_64-unknown-freebsd.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "8907214d7b8d36b518624fb3c4745d9741d3f9a8"
os = "windows"

    [[Nettle.download]]
    sha256 = "e9bd52de1bf72083a5ffe49f0f6fdf32025ae2f149c8e1db17cf6250e29c7cf0"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.1+0/Nettle.v3.10.1.x86_64-w64-mingw32.tar.gz"
