[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "072fea82c6a9ec5e1cfc93e85e30769c7c7de7b0"
os = "macos"

    [[Nettle.download]]
    sha256 = "9a66c23dd781ba69d30ea477916b052f57f433f867bab16dbed870e9a6a0f76d"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.7.2+0/Nettle.v3.7.2.aarch64-apple-darwin.tar.gz"
[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "b6e653990feb88a33c31a76866320e0526d06d8c"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "d09857aa72a0bf98faa21b9e36cbf730c6061f15cce2bcccadaecf7b1334fa10"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.7.2+0/Nettle.v3.7.2.aarch64-linux-gnu.tar.gz"
[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "f68c73c0ad59a1b61cc106b2b09c1d14d1783920"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "05b115828a81edc0a9d70c7ea6daad0e651a8adc3079b65d8d46cee3d306de43"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.7.2+0/Nettle.v3.7.2.aarch64-linux-musl.tar.gz"
[[Nettle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3935ff85c1da3d27c8184a298aa0b53b82ee57f1"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "f7f9eb61716cb7886a5bdd24f8ee0b89e0ebe0392fe42c30cba6b9f0ab57d4e7"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.7.2+0/Nettle.v3.7.2.armv6l-linux-gnueabihf.tar.gz"
[[Nettle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ab6924cc9fb74c08b296cadc78f52ce00f565564"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "fb280cdfd4ca073f24b7b54701a6207ea62cbfcfec6f625d5de685f79b842b08"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.7.2+0/Nettle.v3.7.2.armv6l-linux-musleabihf.tar.gz"
[[Nettle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b28eee3b3eb31c5ba7e5aff7a06101e90b15d368"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "b9672e22db9b0837ffad98dbb1da218dd4dadee921933913982e97a89d33bdc3"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.7.2+0/Nettle.v3.7.2.armv7l-linux-gnueabihf.tar.gz"
[[Nettle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "40ae698eb11ec62c0310a8db5408885a5eb31533"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "1c0a14d5d6591061c4ca2b43864f0dab044adc11e3da54c56fcba66e9095b5b6"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.7.2+0/Nettle.v3.7.2.armv7l-linux-musleabihf.tar.gz"
[[Nettle]]
arch = "i686"
git-tree-sha1 = "8206ed36054b8f07068c212806b65c9dfdccf906"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "6528c4b39351feb861934a40163edbcc58db983da2f0527d900432cf19128fa0"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.7.2+0/Nettle.v3.7.2.i686-linux-gnu.tar.gz"
[[Nettle]]
arch = "i686"
git-tree-sha1 = "b630bf36f6eac3def18dabcc641d9e94be800a9d"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "5464573313c06735fb6f7e9846145fdfed5a4ce5d490b78316807e47ae7019d8"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.7.2+0/Nettle.v3.7.2.i686-linux-musl.tar.gz"
[[Nettle]]
arch = "i686"
git-tree-sha1 = "2a73073f6fc206b8c9fe9432caeede08f0c575e7"
os = "windows"

    [[Nettle.download]]
    sha256 = "0ab8acdf8f693ccb1033d9806b3e615769c91a4613d052c5638a02f7851f6d7b"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.7.2+0/Nettle.v3.7.2.i686-w64-mingw32.tar.gz"
[[Nettle]]
arch = "powerpc64le"
git-tree-sha1 = "4075ee2dc7dfb830f1693f6a18f108317b4a2a71"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "2291a6f3b30ddd814ef85be9865521cdca5164141c82e87e8a7c178cc1d84efd"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.7.2+0/Nettle.v3.7.2.powerpc64le-linux-gnu.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "b4c321da84282acd93ddc5b753cbb947bb24f4bc"
os = "macos"

    [[Nettle.download]]
    sha256 = "9191f8505c80f2bb8f132cb9c98964e55fbdca3792150f62d82ded3d64127a4a"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.7.2+0/Nettle.v3.7.2.x86_64-apple-darwin.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "8f554fe52281d229eeb6ac5da6f3b2f4873360e6"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "8855cea75f70426d98fe61a13cbb6c09973546866dd1be9d9d5bb279c5e4db87"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.7.2+0/Nettle.v3.7.2.x86_64-linux-gnu.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "fe87b3ed56851bc7cb90fbf3718fd6f2b1c22c00"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "edef3f5e2ce1d5c25ca4a086a1ebf0f353941ba2df4fe23771e74a24ec965787"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.7.2+0/Nettle.v3.7.2.x86_64-linux-musl.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "ccf41099dbe0aafffb5f3d9a06cdebe5badcf7ed"
os = "freebsd"

    [[Nettle.download]]
    sha256 = "c95f505d42dc553df2519673ff45775f36ee2acffd71670017a4ed2b6f002fc0"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.7.2+0/Nettle.v3.7.2.x86_64-unknown-freebsd.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "37525cc9eaf85b842f383cbf893840de441f446a"
os = "windows"

    [[Nettle.download]]
    sha256 = "5a68b75c5660e2eccb5066a3b527113f5d388370fe35c507e514dcd946a265e5"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.7.2+0/Nettle.v3.7.2.x86_64-w64-mingw32.tar.gz"
