[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "f28216d6f985c5aa67283ba8278bc74cc66927e0"
os = "macos"

    [[Nettle.download]]
    sha256 = "338f7e9bc3b40fda125bcf62f21b6cd97f77dea1215fbec099f39aa43eb20b6e"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+0/Nettle.v3.10.0.aarch64-apple-darwin.tar.gz"
[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "7cdee03fd6df834f3e29ca6d5f790406cba8d239"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "fc3be55cb138340c8c52549d2365b4d35e457af496693c0e8dba2f34d784efa1"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+0/Nettle.v3.10.0.aarch64-linux-gnu.tar.gz"
[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "85e117891437cd2f14e99b5501c18753ad517dc8"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "8f1970d2fb559d8c7b90a11a753a4dcef9500fa4b5eb9f00cc62f6616a5659ce"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+0/Nettle.v3.10.0.aarch64-linux-musl.tar.gz"
[[Nettle]]
arch = "aarch64"
git-tree-sha1 = "395e18b5685a610a4832cebf287f06b47fa2f6ec"
os = "freebsd"

    [[Nettle.download]]
    sha256 = "c61cea9d739136c81da34933b49d40c4fc63a201f6a9c8bf1a2ff2b387599459"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+0/Nettle.v3.10.0.aarch64-unknown-freebsd.tar.gz"
[[Nettle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a0e6b53b0203125ef963bc3101503384e68958e8"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "057d93ad3441a8034782eb18cc0a8861b604de022d55134c536dfe004d3491c9"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+0/Nettle.v3.10.0.armv6l-linux-gnueabihf.tar.gz"
[[Nettle]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b09189bc30e189c95308c5be69fa2819eb5b3400"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "44e18280c9f0d114409ce3a750fe470f7d8a7d144b356212e8ed713e0dee59a0"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+0/Nettle.v3.10.0.armv6l-linux-musleabihf.tar.gz"
[[Nettle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6e1c40c61e4ea18b594fc99de8d4b113e0793b6d"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "0e342f3f6f7e7defd98cd9b3049c36a89d3fbdceb0a8ac2a6f1a9c46a215dd8f"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+0/Nettle.v3.10.0.armv7l-linux-gnueabihf.tar.gz"
[[Nettle]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d006b10120b86bd88c44e886c4a29841206133ff"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "1be8dc76ea720eab43433172584d0563e37de9b98d557421d702806992668c1b"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+0/Nettle.v3.10.0.armv7l-linux-musleabihf.tar.gz"
[[Nettle]]
arch = "i686"
git-tree-sha1 = "b69dad7229a2e164ec438d59e3d91d553bc7f636"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "80fc8f1ba17198e8ae866180a90c28b6a3efbd92f3042f827d449c37d4a6c4cb"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+0/Nettle.v3.10.0.i686-linux-gnu.tar.gz"
[[Nettle]]
arch = "i686"
git-tree-sha1 = "b6a21471787696ad7f6c379dc671e63acd4dd362"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "bf764cda0b40871d70cedeeb9ce69d2c45c2736c081d6223fa152943f013389a"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+0/Nettle.v3.10.0.i686-linux-musl.tar.gz"
[[Nettle]]
arch = "i686"
git-tree-sha1 = "f203ebf2037bd7b7d8bc4bf00980a363d1b661c8"
os = "windows"

    [[Nettle.download]]
    sha256 = "c1a9d5df531a6a29bf3442f373fb093ba95b924b5ea7232a88cf831eb6f234a7"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+0/Nettle.v3.10.0.i686-w64-mingw32.tar.gz"
[[Nettle]]
arch = "powerpc64le"
git-tree-sha1 = "64ebdc7c8b662be6434b4c40f3946b87cb533978"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "9ddf90cc2c726852d7725209092332ecd505afec9387ceea525dd903bd572c8b"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+0/Nettle.v3.10.0.powerpc64le-linux-gnu.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "847bc4b5cf2afbe8a44a2ec3b01feba3a068f469"
os = "macos"

    [[Nettle.download]]
    sha256 = "bea9d7f0050728efe982df547f3c6dbd79c8c0f49548fedf3b0fb1a0aa655107"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+0/Nettle.v3.10.0.x86_64-apple-darwin.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "231521bbdc8f4acc21d37cf50a1304cc49b7484c"
libc = "glibc"
os = "linux"

    [[Nettle.download]]
    sha256 = "95b346e64ef95d2ea04624de6debfb54fab9ff7cf2a98c59bd32a0dda1325efc"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+0/Nettle.v3.10.0.x86_64-linux-gnu.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "37ec34354eb9318f77a481fd861b4ef4be4fc585"
libc = "musl"
os = "linux"

    [[Nettle.download]]
    sha256 = "7ed65df3059c592d1d0d582ad73aa2dbb26ffc06bcd5b18a2936915517b31cc5"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+0/Nettle.v3.10.0.x86_64-linux-musl.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "624229f6650c8593cdcf920e770373571f3f243e"
os = "freebsd"

    [[Nettle.download]]
    sha256 = "3baa59330f5bb450831dff1b954f96e74e388fb43cb3a323bc7eecd09927dad1"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+0/Nettle.v3.10.0.x86_64-unknown-freebsd.tar.gz"
[[Nettle]]
arch = "x86_64"
git-tree-sha1 = "fa9fbd2a9ff7b20ba249123d7846e464b7c86e21"
os = "windows"

    [[Nettle.download]]
    sha256 = "1a8d9bc84f89384732d488592dab3e5ac8370f328e9ab23a7fd6ea8fb93f4e14"
    url = "https://github.com/JuliaBinaryWrappers/Nettle_jll.jl/releases/download/Nettle-v3.10.0+0/Nettle.v3.10.0.x86_64-w64-mingw32.tar.gz"
