# Autogenerated wrapper script for Nettle_jll for i686-w64-mingw32
export libhogweed, libnettle, nettle_hash

using GMP_jll
JLLWrappers.@generate_wrapper_header("Nettle")
JLLWrappers.@declare_library_product(libhogweed, "libhogweed-4.dll")
JLLWrappers.@declare_library_product(libnettle, "libnettle-6.dll")
JLLWrappers.@declare_executable_product(nettle_hash)
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll)
    JLLWrappers.@init_library_product(
        libhogweed,
        "bin\\libhogweed-4.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnettle,
        "bin\\libnettle-6.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        nettle_hash,
        "bin\\nettle-hash.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
