# Autogenerated wrapper script for Nettle_jll for x86_64-apple-darwin
export libhogweed, libnettle, nettle_hash

using GMP_jll
JLLWrappers.@generate_wrapper_header("Nettle")
JLLWrappers.@declare_library_product(libhogweed, "@rpath/libhogweed.6.dylib")
JLLWrappers.@declare_library_product(libnettle, "@rpath/libnettle.8.dylib")
JLLWrappers.@declare_executable_product(nettle_hash)
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll)
    JLLWrappers.@init_library_product(
        libhogweed,
        "lib/libhogweed.6.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnettle,
        "lib/libnettle.8.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        nettle_hash,
        "bin/nettle-hash",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
